version: '3.8'

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mpapin/data/db
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mpapin/data/wordpress

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    secrets:
      - db_password
      - db_root_password
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: on-failure
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    secrets:
      - db_password
      - credentials
    env_file:
      - .env

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: on-failure
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    ports:
      - "443:443"
    env_file:
      - .env